name: Build and Package

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use Personal Access Token for dependency resolution
      - name: Set up JDK 24 (for dependencies)
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          server-id: github
          server-username: ady88
          server-password: PACKAGES_TOKEN

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clean and compile
        run: mvn clean compile
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Run tests
        run: mvn test
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Package JAR
        run: mvn package
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: helper-lib-jar
          path: target/*.jar
          retention-days: 30

      # Reconfigure Maven for deployment with GITHUB_TOKEN
      - name: Set up JDK 24 (for deployment)
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: GITHUB_TOKEN

      - name: Deploy to GitHub Packages
        run: mvn deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}